// Code generated by otigen. DO NOT EDIT.
//
// Wires this contract's otigen.toml to the Pyde host ABI:
// //go:wasmexport dispatch + typed State accessors. Regenerated
// on every `otigen build`.

//go:build tinygo

package main

import pyde "github.com/pyde-net/pyde-host/go"

var _ = pyde.StatusOK

// ── State ──────────────────────────────────────────────────────────

// State is the typed view of this contract's [state] schema.
var State = struct {
	NextKey  __stateNextKey
	Created  __stateCreated
	Children __stateChildren
	Named    __stateNamed
}{}

type __stateNextKey struct{}

// Get reads the "next_key" scalar, returning the zero value if unset.
func (__stateNextKey) Get() uint64 {
	b, ok := pyde.LoadScalar("next_key")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "next_key" scalar.
func (__stateNextKey) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("next_key", e.Finish())
}

type __stateCreated struct{}

// Get reads the "created" scalar, returning the zero value if unset.
func (__stateCreated) Get() uint64 {
	b, ok := pyde.LoadScalar("created")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "created" scalar.
func (__stateCreated) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("created", e.Finish())
}

type __stateChildren struct{}

// Get reads "children"[keys], returning the zero value if unset.
func (__stateChildren) Get(k0 uint64) pyde.Address {
	b, ok := pyde.LoadMap1("children", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes "children"[keys] = v.
func (__stateChildren) Set(k0 uint64, v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreMap1("children", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "children"[keys].
func (__stateChildren) Delete(k0 uint64) {
	pyde.DeleteMap1("children", pyde.NewEncoder().U64(k0).Finish())
}

type __stateNamed struct{}

// Get reads "named"[keys], returning the zero value if unset.
func (__stateNamed) Get(k0 string) pyde.Address {
	b, ok := pyde.LoadMap1("named", pyde.NewEncoder().String(k0).Finish())
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes "named"[keys] = v.
func (__stateNamed) Set(k0 string, v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreMap1("named", pyde.NewEncoder().String(k0).Finish(), e.Finish())
}

// Delete clears "named"[keys].
func (__stateNamed) Delete(k0 string) {
	pyde.DeleteMap1("named", pyde.NewEncoder().String(k0).Finish())
}

// ── Dispatch ───────────────────────────────────────────────────────

//go:wasmexport bump
func __pyde_export_bump() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__r := Bump(__a0)
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport bump_at
func __pyde_export_bump_at() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__r := BumpAt(__a0)
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport bump_named
func __pyde_export_bump_named() {
	__d := pyde.Args()
	__a0 := __d.String()
	__r := BumpNamed(__a0)
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport child_of
func __pyde_export_child_of() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__r := ChildOf(__a0)
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport child_of_name
func __pyde_export_child_of_name() {
	__d := pyde.Args()
	__a0 := __d.String()
	__r := ChildOfName(__a0)
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport create
func __pyde_export_create() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__r := Create(__a0)
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport create_named
func __pyde_export_create_named() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.String()
	__r := CreateNamed(__a0, __a1)
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport create_with_key
func __pyde_export_create_with_key() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.U64()
	__r := CreateWithKey(__a0, __a1)
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport created
func __pyde_export_created() {
	__r := Created()
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport next_key
func __pyde_export_next_key() {
	__r := NextKey()
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}
