// Code generated by otigen. DO NOT EDIT.
//
// Wires this contract's otigen.toml to the Pyde host ABI:
// //go:wasmexport dispatch + typed State accessors. Regenerated
// on every `otigen build`.

//go:build tinygo

package main

import pyde "github.com/pyde-net/pyde-host/go"

var _ = pyde.StatusOK

// ── State ──────────────────────────────────────────────────────────

// State is the typed view of this contract's [state] schema.
var State = struct {
	Beneficiary     __stateBeneficiary
	TotalAmount     __stateTotalAmount
	StartTime       __stateStartTime
	CliffSeconds    __stateCliffSeconds
	DurationSeconds __stateDurationSeconds
	Released        __stateReleased
	Configured      __stateConfigured
}{}

type __stateBeneficiary struct{}

// Get reads the "beneficiary" scalar, returning the zero value if unset.
func (__stateBeneficiary) Get() pyde.Address {
	b, ok := pyde.LoadScalar("beneficiary")
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes the "beneficiary" scalar.
func (__stateBeneficiary) Set(v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreScalar("beneficiary", e.Finish())
}

type __stateTotalAmount struct{}

// Get reads the "total_amount" scalar, returning the zero value if unset.
func (__stateTotalAmount) Get() pyde.U128 {
	b, ok := pyde.LoadScalar("total_amount")
	if !ok {
		return pyde.U128{}
	}
	d := pyde.NewDecoder(b)
	return d.U128()
}

// Set writes the "total_amount" scalar.
func (__stateTotalAmount) Set(v pyde.U128) {
	e := pyde.NewEncoder()
	e.U128(v)
	pyde.StoreScalar("total_amount", e.Finish())
}

type __stateStartTime struct{}

// Get reads the "start_time" scalar, returning the zero value if unset.
func (__stateStartTime) Get() uint64 {
	b, ok := pyde.LoadScalar("start_time")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "start_time" scalar.
func (__stateStartTime) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("start_time", e.Finish())
}

type __stateCliffSeconds struct{}

// Get reads the "cliff_seconds" scalar, returning the zero value if unset.
func (__stateCliffSeconds) Get() uint64 {
	b, ok := pyde.LoadScalar("cliff_seconds")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "cliff_seconds" scalar.
func (__stateCliffSeconds) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("cliff_seconds", e.Finish())
}

type __stateDurationSeconds struct{}

// Get reads the "duration_seconds" scalar, returning the zero value if unset.
func (__stateDurationSeconds) Get() uint64 {
	b, ok := pyde.LoadScalar("duration_seconds")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "duration_seconds" scalar.
func (__stateDurationSeconds) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("duration_seconds", e.Finish())
}

type __stateReleased struct{}

// Get reads the "released" scalar, returning the zero value if unset.
func (__stateReleased) Get() pyde.U128 {
	b, ok := pyde.LoadScalar("released")
	if !ok {
		return pyde.U128{}
	}
	d := pyde.NewDecoder(b)
	return d.U128()
}

// Set writes the "released" scalar.
func (__stateReleased) Set(v pyde.U128) {
	e := pyde.NewEncoder()
	e.U128(v)
	pyde.StoreScalar("released", e.Finish())
}

type __stateConfigured struct{}

// Get reads the "configured" scalar, returning the zero value if unset.
func (__stateConfigured) Get() bool {
	b, ok := pyde.LoadScalar("configured")
	if !ok {
		return false
	}
	d := pyde.NewDecoder(b)
	return d.Bool()
}

// Set writes the "configured" scalar.
func (__stateConfigured) Set(v bool) {
	e := pyde.NewEncoder()
	e.Bool(v)
	pyde.StoreScalar("configured", e.Finish())
}

// ── Events ─────────────────────────────────────────────────────────

// Configured is the Configured(address,uint128,uint64,uint64,uint64) event. Emit it with a named-field
// literal: Configured{...}.Emit().
type Configured struct {
	Beneficiary     pyde.Address
	TotalAmount     pyde.U128
	StartTime       uint64
	CliffSeconds    uint64
	DurationSeconds uint64
}

// Emit appends this Configured event to the receipt.
func (ev Configured) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Configured(address,uint128,uint64,uint64,uint64)"),
		pyde.Bytes32(ev.Beneficiary),
	}
	e := pyde.NewEncoder()
	e.U128(ev.TotalAmount)
	e.U64(ev.StartTime)
	e.U64(ev.CliffSeconds)
	e.U64(ev.DurationSeconds)
	pyde.Emit(topics, e.Finish())
}

// Funded is the Funded(address,uint128) event. Emit it with a named-field
// literal: Funded{...}.Emit().
type Funded struct {
	From   pyde.Address
	Amount pyde.U128
}

// Emit appends this Funded event to the receipt.
func (ev Funded) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Funded(address,uint128)"),
		pyde.Bytes32(ev.From),
	}
	e := pyde.NewEncoder()
	e.U128(ev.Amount)
	pyde.Emit(topics, e.Finish())
}

// Released is the Released(address,uint128,uint128) event. Emit it with a named-field
// literal: Released{...}.Emit().
type Released struct {
	Beneficiary   pyde.Address
	Amount        pyde.U128
	TotalReleased pyde.U128
}

// Emit appends this Released event to the receipt.
func (ev Released) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Released(address,uint128,uint128)"),
		pyde.Bytes32(ev.Beneficiary),
	}
	e := pyde.NewEncoder()
	e.U128(ev.Amount)
	e.U128(ev.TotalReleased)
	pyde.Emit(topics, e.Finish())
}

// ── Dispatch ───────────────────────────────────────────────────────

//go:wasmexport configure
func __pyde_export_configure() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.U128()
	__a2 := __d.U64()
	__a3 := __d.U64()
	__a4 := __d.U64()
	Configure(__a0, __a1, __a2, __a3, __a4)
	pyde.ReturnNothing()
}

//go:wasmexport configured_flag
func __pyde_export_configured_flag() {
	__r := ConfiguredFlag()
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport fund
func __pyde_export_fund() {
	Fund()
	pyde.ReturnNothing()
}

//go:wasmexport releasable
func __pyde_export_releasable() {
	__r := Releasable()
	__e := pyde.NewEncoder()
	__e.U128(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport release
func __pyde_export_release() {
	__r := Release()
	__e := pyde.NewEncoder()
	__e.U128(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport released_amount
func __pyde_export_released_amount() {
	__r := ReleasedAmount()
	__e := pyde.NewEncoder()
	__e.U128(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport vested_amount
func __pyde_export_vested_amount() {
	__r := VestedAmount()
	__e := pyde.NewEncoder()
	__e.U128(__r)
	pyde.Return(__e.Finish())
}
