// Code generated by otigen. DO NOT EDIT.
//
// Wires this contract's otigen.toml to the Pyde host ABI:
// //go:wasmexport dispatch + typed State accessors. Regenerated
// on every `otigen build`.

//go:build tinygo

package main

import pyde "github.com/pyde-net/pyde-host/go"

var _ = pyde.StatusOK

// ── State ──────────────────────────────────────────────────────────

// State is the typed view of this contract's [state] schema.
var State = struct {
	ProxyAdmin __stateProxyAdmin
	ProxyLogic __stateProxyLogic
	Value      __stateValue
}{}

type __stateProxyAdmin struct{}

// Get reads the "proxy_admin" scalar, returning the zero value if unset.
func (__stateProxyAdmin) Get() pyde.Address {
	b, ok := pyde.LoadScalar("proxy_admin")
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes the "proxy_admin" scalar.
func (__stateProxyAdmin) Set(v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreScalar("proxy_admin", e.Finish())
}

type __stateProxyLogic struct{}

// Get reads the "proxy_logic" scalar, returning the zero value if unset.
func (__stateProxyLogic) Get() pyde.Address {
	b, ok := pyde.LoadScalar("proxy_logic")
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes the "proxy_logic" scalar.
func (__stateProxyLogic) Set(v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreScalar("proxy_logic", e.Finish())
}

type __stateValue struct{}

// Get reads the "value" scalar, returning the zero value if unset.
func (__stateValue) Get() uint64 {
	b, ok := pyde.LoadScalar("value")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "value" scalar.
func (__stateValue) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("value", e.Finish())
}

// ── Events ─────────────────────────────────────────────────────────

// AdminTransferred is the AdminTransferred(address,address) event. Emit it with a named-field
// literal: AdminTransferred{...}.Emit().
type AdminTransferred struct {
	OldAdmin pyde.Address
	NewAdmin pyde.Address
}

// Emit appends this AdminTransferred event to the receipt.
func (ev AdminTransferred) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("AdminTransferred(address,address)"),
		pyde.Bytes32(ev.OldAdmin),
		pyde.Bytes32(ev.NewAdmin),
	}
	pyde.Emit(topics, nil)
}

// Initialized is the Initialized(address,address) event. Emit it with a named-field
// literal: Initialized{...}.Emit().
type Initialized struct {
	Admin        pyde.Address
	InitialLogic pyde.Address
}

// Emit appends this Initialized event to the receipt.
func (ev Initialized) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Initialized(address,address)"),
		pyde.Bytes32(ev.Admin),
		pyde.Bytes32(ev.InitialLogic),
	}
	pyde.Emit(topics, nil)
}

// Upgraded is the Upgraded(address,address) event. Emit it with a named-field
// literal: Upgraded{...}.Emit().
type Upgraded struct {
	OldLogic pyde.Address
	NewLogic pyde.Address
}

// Emit appends this Upgraded event to the receipt.
func (ev Upgraded) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Upgraded(address,address)"),
		pyde.Bytes32(ev.OldLogic),
		pyde.Bytes32(ev.NewLogic),
	}
	pyde.Emit(topics, nil)
}

// ── Dispatch ───────────────────────────────────────────────────────

//go:wasmexport forward
func __pyde_export_forward() {
	__d := pyde.Args()
	__a0 := __d.String()
	__a1 := __d.Bytes()
	__r := Forward(__a0, __a1)
	__e := pyde.NewEncoder()
	__e.Bytes(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport get_admin
func __pyde_export_get_admin() {
	__r := GetAdmin()
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport get_logic
func __pyde_export_get_logic() {
	__r := GetLogic()
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport get_value
func __pyde_export_get_value() {
	__r := GetValue()
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport init
func __pyde_export_init() {
	__d := pyde.Args()
	__a0 := __d.Address()
	Init(__a0)
	pyde.ReturnNothing()
}

//go:wasmexport renounce_admin
func __pyde_export_renounce_admin() {
	RenounceAdmin()
	pyde.ReturnNothing()
}

//go:wasmexport transfer_admin
func __pyde_export_transfer_admin() {
	__d := pyde.Args()
	__a0 := __d.Address()
	TransferAdmin(__a0)
	pyde.ReturnNothing()
}

//go:wasmexport upgrade_to
func __pyde_export_upgrade_to() {
	__d := pyde.Args()
	__a0 := __d.Address()
	UpgradeTo(__a0)
	pyde.ReturnNothing()
}
