// Code generated by otigen. DO NOT EDIT.
//
// Wires this contract's otigen.toml to the Pyde host ABI:
// //go:wasmexport dispatch + typed State accessors. Regenerated
// on every `otigen build`.

//go:build tinygo

package main

import pyde "github.com/pyde-net/pyde-host/go"

var _ = pyde.StatusOK

// ── State ──────────────────────────────────────────────────────────

// State is the typed view of this contract's [state] schema.
var State = struct {
	Owner       __stateOwner
	TotalSupply __stateTotalSupply
	Balances    __stateBalances
	Allowances  __stateAllowances
}{}

type __stateOwner struct{}

// Get reads the "owner" scalar, returning the zero value if unset.
func (__stateOwner) Get() pyde.Address {
	b, ok := pyde.LoadScalar("owner")
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes the "owner" scalar.
func (__stateOwner) Set(v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreScalar("owner", e.Finish())
}

type __stateTotalSupply struct{}

// Get reads the "total_supply" scalar, returning the zero value if unset.
func (__stateTotalSupply) Get() pyde.U128 {
	b, ok := pyde.LoadScalar("total_supply")
	if !ok {
		return pyde.U128{}
	}
	d := pyde.NewDecoder(b)
	return d.U128()
}

// Set writes the "total_supply" scalar.
func (__stateTotalSupply) Set(v pyde.U128) {
	e := pyde.NewEncoder()
	e.U128(v)
	pyde.StoreScalar("total_supply", e.Finish())
}

type __stateBalances struct{}

// Get reads "balances"[keys], returning the zero value if unset.
func (__stateBalances) Get(k0 pyde.Address) pyde.U128 {
	b, ok := pyde.LoadMap1("balances", pyde.NewEncoder().Address(k0).Finish())
	if !ok {
		return pyde.U128{}
	}
	d := pyde.NewDecoder(b)
	return d.U128()
}

// Set writes "balances"[keys] = v.
func (__stateBalances) Set(k0 pyde.Address, v pyde.U128) {
	e := pyde.NewEncoder()
	e.U128(v)
	pyde.StoreMap1("balances", pyde.NewEncoder().Address(k0).Finish(), e.Finish())
}

// Delete clears "balances"[keys].
func (__stateBalances) Delete(k0 pyde.Address) {
	pyde.DeleteMap1("balances", pyde.NewEncoder().Address(k0).Finish())
}

type __stateAllowances struct{}

// Get reads "allowances"[keys], returning the zero value if unset.
func (__stateAllowances) Get(k0 pyde.Address, k1 pyde.Address) pyde.U128 {
	b, ok := pyde.LoadMap2("allowances", pyde.NewEncoder().Address(k0).Finish(), pyde.NewEncoder().Address(k1).Finish())
	if !ok {
		return pyde.U128{}
	}
	d := pyde.NewDecoder(b)
	return d.U128()
}

// Set writes "allowances"[keys] = v.
func (__stateAllowances) Set(k0 pyde.Address, k1 pyde.Address, v pyde.U128) {
	e := pyde.NewEncoder()
	e.U128(v)
	pyde.StoreMap2("allowances", pyde.NewEncoder().Address(k0).Finish(), pyde.NewEncoder().Address(k1).Finish(), e.Finish())
}

// Delete clears "allowances"[keys].
func (__stateAllowances) Delete(k0 pyde.Address, k1 pyde.Address) {
	pyde.DeleteMap2("allowances", pyde.NewEncoder().Address(k0).Finish(), pyde.NewEncoder().Address(k1).Finish())
}

// ── Events ─────────────────────────────────────────────────────────

// EmitApproval appends a Approval event to the receipt.
func EmitApproval(owner pyde.Address, spender pyde.Address, amount pyde.U128) {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Approval(address,address,uint128)"),
		pyde.Bytes32(owner),
		pyde.Bytes32(spender),
	}
	e := pyde.NewEncoder()
	e.U128(amount)
	pyde.Emit(topics, e.Finish())
}

// EmitTransfer appends a Transfer event to the receipt.
func EmitTransfer(from pyde.Address, to pyde.Address, amount pyde.U128) {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Transfer(address,address,uint128)"),
		pyde.Bytes32(from),
		pyde.Bytes32(to),
	}
	e := pyde.NewEncoder()
	e.U128(amount)
	pyde.Emit(topics, e.Finish())
}

// ── Dispatch ───────────────────────────────────────────────────────

//go:wasmexport allowance
func __pyde_export_allowance() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.Address()
	__r := Allowance(__a0, __a1)
	__e := pyde.NewEncoder()
	__e.U128(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport approve
func __pyde_export_approve() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.U128()
	__r := Approve(__a0, __a1)
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport balance_of
func __pyde_export_balance_of() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__r := BalanceOf(__a0)
	__e := pyde.NewEncoder()
	__e.U128(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport init
func __pyde_export_init() {
	__d := pyde.Args()
	__a0 := __d.U128()
	Init(__a0)
	pyde.ReturnNothing()
}

//go:wasmexport mint
func __pyde_export_mint() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.U128()
	Mint(__a0, __a1)
	pyde.ReturnNothing()
}

//go:wasmexport owner
func __pyde_export_owner() {
	__r := Owner()
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport total_supply
func __pyde_export_total_supply() {
	__r := TotalSupply()
	__e := pyde.NewEncoder()
	__e.U128(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport transfer
func __pyde_export_transfer() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.U128()
	__r := Transfer(__a0, __a1)
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport transfer_from
func __pyde_export_transfer_from() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.Address()
	__a2 := __d.U128()
	__r := TransferFrom(__a0, __a1, __a2)
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}
