// Code generated by otigen. DO NOT EDIT.
//
// Wires this contract's otigen.toml to the Pyde host ABI:
// //go:wasmexport dispatch + typed State accessors. Regenerated
// on every `otigen build`.

//go:build tinygo

package main

import pyde "github.com/pyde-net/pyde-host/go"

var _ = pyde.StatusOK

// ── State ──────────────────────────────────────────────────────────

// State is the typed view of this contract's [state] schema.
var State = struct {
	Admin        __stateAdmin
	MerkleRoot   __stateMerkleRoot
	RootSet      __stateRootSet
	TotalClaimed __stateTotalClaimed
	Claimed      __stateClaimed
}{}

type __stateAdmin struct{}

// Get reads the "admin" scalar, returning the zero value if unset.
func (__stateAdmin) Get() pyde.Address {
	b, ok := pyde.LoadScalar("admin")
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes the "admin" scalar.
func (__stateAdmin) Set(v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreScalar("admin", e.Finish())
}

type __stateMerkleRoot struct{}

// Get reads the "merkle_root" scalar, returning the zero value if unset.
func (__stateMerkleRoot) Get() pyde.Bytes32 {
	b, ok := pyde.LoadScalar("merkle_root")
	if !ok {
		return pyde.Bytes32{}
	}
	d := pyde.NewDecoder(b)
	return d.Bytes32()
}

// Set writes the "merkle_root" scalar.
func (__stateMerkleRoot) Set(v pyde.Bytes32) {
	e := pyde.NewEncoder()
	e.Bytes32(v)
	pyde.StoreScalar("merkle_root", e.Finish())
}

type __stateRootSet struct{}

// Get reads the "root_set" scalar, returning the zero value if unset.
func (__stateRootSet) Get() bool {
	b, ok := pyde.LoadScalar("root_set")
	if !ok {
		return false
	}
	d := pyde.NewDecoder(b)
	return d.Bool()
}

// Set writes the "root_set" scalar.
func (__stateRootSet) Set(v bool) {
	e := pyde.NewEncoder()
	e.Bool(v)
	pyde.StoreScalar("root_set", e.Finish())
}

type __stateTotalClaimed struct{}

// Get reads the "total_claimed" scalar, returning the zero value if unset.
func (__stateTotalClaimed) Get() pyde.U128 {
	b, ok := pyde.LoadScalar("total_claimed")
	if !ok {
		return pyde.U128{}
	}
	d := pyde.NewDecoder(b)
	return d.U128()
}

// Set writes the "total_claimed" scalar.
func (__stateTotalClaimed) Set(v pyde.U128) {
	e := pyde.NewEncoder()
	e.U128(v)
	pyde.StoreScalar("total_claimed", e.Finish())
}

type __stateClaimed struct{}

// Get reads "claimed"[keys], returning the zero value if unset.
func (__stateClaimed) Get(k0 pyde.Address) bool {
	b, ok := pyde.LoadMap1("claimed", pyde.NewEncoder().Address(k0).Finish())
	if !ok {
		return false
	}
	d := pyde.NewDecoder(b)
	return d.Bool()
}

// Set writes "claimed"[keys] = v.
func (__stateClaimed) Set(k0 pyde.Address, v bool) {
	e := pyde.NewEncoder()
	e.Bool(v)
	pyde.StoreMap1("claimed", pyde.NewEncoder().Address(k0).Finish(), e.Finish())
}

// Delete clears "claimed"[keys].
func (__stateClaimed) Delete(k0 pyde.Address) {
	pyde.DeleteMap1("claimed", pyde.NewEncoder().Address(k0).Finish())
}

// ── Events ─────────────────────────────────────────────────────────

// ClaimEvent is the Claim(address,uint128) event. Emit it with a named-field
// literal: ClaimEvent{...}.Emit().
type ClaimEvent struct {
	Claimant pyde.Address
	Amount   pyde.U128
}

// Emit appends this Claim event to the receipt.
func (ev ClaimEvent) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Claim(address,uint128)"),
		pyde.Bytes32(ev.Claimant),
	}
	e := pyde.NewEncoder()
	e.U128(ev.Amount)
	pyde.Emit(topics, e.Finish())
}

// Funded is the Funded(address,uint128) event. Emit it with a named-field
// literal: Funded{...}.Emit().
type Funded struct {
	From   pyde.Address
	Amount pyde.U128
}

// Emit appends this Funded event to the receipt.
func (ev Funded) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Funded(address,uint128)"),
		pyde.Bytes32(ev.From),
	}
	e := pyde.NewEncoder()
	e.U128(ev.Amount)
	pyde.Emit(topics, e.Finish())
}

// ── Dispatch ───────────────────────────────────────────────────────

//go:wasmexport claim
func __pyde_export_claim() {
	__d := pyde.Args()
	__a0 := __d.U128()
	__a1 := __d.Bytes()
	Claim(__a0, __a1)
	pyde.ReturnNothing()
}

//go:wasmexport fund
func __pyde_export_fund() {
	Fund()
	pyde.ReturnNothing()
}

//go:wasmexport init
func __pyde_export_init() {
	Init()
	pyde.ReturnNothing()
}

//go:wasmexport is_claimed
func __pyde_export_is_claimed() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__r := IsClaimed(__a0)
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport merkle_root_first_byte
func __pyde_export_merkle_root_first_byte() {
	__r := MerkleRootFirstByte()
	__e := pyde.NewEncoder()
	__e.I64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport set_root
func __pyde_export_set_root() {
	__d := pyde.Args()
	__a0 := __d.Bytes32()
	SetRoot(__a0)
	pyde.ReturnNothing()
}

//go:wasmexport total_claimed
func __pyde_export_total_claimed() {
	__r := TotalClaimed()
	__e := pyde.NewEncoder()
	__e.U128(__r)
	pyde.Return(__e.Finish())
}
