// Code generated by otigen. DO NOT EDIT.
//
// Wires this contract's otigen.toml to the Pyde host ABI:
// //go:wasmexport dispatch + typed State accessors. Regenerated
// on every `otigen build`.

//go:build tinygo

package main

import pyde "github.com/pyde-net/pyde-host/go"

var _ = pyde.StatusOK

// ── State ──────────────────────────────────────────────────────────

// State is the typed view of this contract's [state] schema.
var State = struct {
	Threshold __stateThreshold
	Signers   __stateSigners
	Used      __stateUsed
}{}

type __stateThreshold struct{}

// Get reads the "threshold" scalar, returning the zero value if unset.
func (__stateThreshold) Get() uint8 {
	b, ok := pyde.LoadScalar("threshold")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U8()
}

// Set writes the "threshold" scalar.
func (__stateThreshold) Set(v uint8) {
	e := pyde.NewEncoder()
	e.U8(v)
	pyde.StoreScalar("threshold", e.Finish())
}

type __stateSigners struct{}

// Get reads "signers"[keys], returning the zero value if unset.
func (__stateSigners) Get(k0 uint8) pyde.Bytes32 {
	b, ok := pyde.LoadMap1("signers", pyde.NewEncoder().U8(k0).Finish())
	if !ok {
		return pyde.Bytes32{}
	}
	d := pyde.NewDecoder(b)
	return d.Bytes32()
}

// Set writes "signers"[keys] = v.
func (__stateSigners) Set(k0 uint8, v pyde.Bytes32) {
	e := pyde.NewEncoder()
	e.Bytes32(v)
	pyde.StoreMap1("signers", pyde.NewEncoder().U8(k0).Finish(), e.Finish())
}

// Delete clears "signers"[keys].
func (__stateSigners) Delete(k0 uint8) {
	pyde.DeleteMap1("signers", pyde.NewEncoder().U8(k0).Finish())
}

type __stateUsed struct{}

// Get reads "used"[keys], returning the zero value if unset.
func (__stateUsed) Get(k0 pyde.Bytes32) bool {
	b, ok := pyde.LoadMap1("used", pyde.NewEncoder().Bytes32(k0).Finish())
	if !ok {
		return false
	}
	d := pyde.NewDecoder(b)
	return d.Bool()
}

// Set writes "used"[keys] = v.
func (__stateUsed) Set(k0 pyde.Bytes32, v bool) {
	e := pyde.NewEncoder()
	e.Bool(v)
	pyde.StoreMap1("used", pyde.NewEncoder().Bytes32(k0).Finish(), e.Finish())
}

// Delete clears "used"[keys].
func (__stateUsed) Delete(k0 pyde.Bytes32) {
	pyde.DeleteMap1("used", pyde.NewEncoder().Bytes32(k0).Finish())
}

// ── Events ─────────────────────────────────────────────────────────

// Executed is the Executed(address,uint128,bytes32) event. Emit it with a named-field
// literal: Executed{...}.Emit().
type Executed struct {
	Target       pyde.Address
	Amount       pyde.U128
	ActionDigest pyde.Bytes32
}

// Emit appends this Executed event to the receipt.
func (ev Executed) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Executed(address,uint128,bytes32)"),
		pyde.Bytes32(ev.Target),
		pyde.Bytes32(ev.ActionDigest),
	}
	e := pyde.NewEncoder()
	e.U128(ev.Amount)
	pyde.Emit(topics, e.Finish())
}

// ── Dispatch ───────────────────────────────────────────────────────

//go:wasmexport action_digest
func __pyde_export_action_digest() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.U128()
	__a2 := __d.U128()
	__r := ActionDigest(__a0, __a1, __a2)
	__e := pyde.NewEncoder()
	__e.Bytes32(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport execute
func __pyde_export_execute() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.U128()
	__a2 := __d.U128()
	__a3 := __d.Bytes()
	__a4 := __d.Bytes()
	__a5 := __d.Bytes()
	__a6 := __d.Bytes()
	__a7 := __d.Bytes()
	__a8 := __d.Bytes()
	Execute(__a0, __a1, __a2, __a3, __a4, __a5, __a6, __a7, __a8)
	pyde.ReturnNothing()
}

//go:wasmexport get_threshold
func __pyde_export_get_threshold() {
	__r := GetThreshold()
	__e := pyde.NewEncoder()
	__e.U8(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport init
func __pyde_export_init() {
	__d := pyde.Args()
	__a0 := __d.U8()
	__a1 := __d.Bytes32()
	__a2 := __d.Bytes32()
	__a3 := __d.Bytes32()
	Init(__a0, __a1, __a2, __a3)
	pyde.ReturnNothing()
}

//go:wasmexport is_used
func __pyde_export_is_used() {
	__d := pyde.Args()
	__a0 := __d.Bytes32()
	__r := IsUsed(__a0)
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}
