// Code generated by otigen. DO NOT EDIT.
//
// Wires this contract's otigen.toml to the Pyde host ABI:
// //go:wasmexport dispatch + typed State accessors. Regenerated
// on every `otigen build`.

//go:build tinygo

package main

import pyde "github.com/pyde-net/pyde-host/go"

var _ = pyde.StatusOK

// ── Vec codecs ─────────────────────────────────────────────────────

func __encodeVecU8(e *pyde.Encoder, v []uint8) {
	e.U32(uint32(len(v)))
	for _, x := range v {
		e.U8(x)
	}
}

func __decodeVecU8(d *pyde.Decoder) []uint8 {
	n := int(d.U32())
	out := make([]uint8, n)
	for i := range out {
		out[i] = d.U8()
	}
	return out
}

// ── State ──────────────────────────────────────────────────────────

// State is the typed view of this contract's [state] schema.
var State = struct {
	TokenName         __stateTokenName
	TokenSymbol       __stateTokenSymbol
	TotalSupply       __stateTotalSupply
	MaxSupply         __stateMaxSupply
	NextId            __stateNextId
	Minter            __stateMinter
	Manager           __stateManager
	Owners            __stateOwners
	Balances          __stateBalances
	TokenApprovals    __stateTokenApprovals
	OperatorApprovals __stateOperatorApprovals
	TokenUris         __stateTokenUris
}{}

type __stateTokenName struct{}

// Get reads the "token_name" scalar, returning the zero value if unset.
func (__stateTokenName) Get() string {
	b, ok := pyde.LoadScalar("token_name")
	if !ok {
		return ""
	}
	d := pyde.NewDecoder(b)
	return d.String()
}

// Set writes the "token_name" scalar.
func (__stateTokenName) Set(v string) {
	e := pyde.NewEncoder()
	e.String(v)
	pyde.StoreScalar("token_name", e.Finish())
}

type __stateTokenSymbol struct{}

// Get reads the "token_symbol" scalar, returning the zero value if unset.
func (__stateTokenSymbol) Get() string {
	b, ok := pyde.LoadScalar("token_symbol")
	if !ok {
		return ""
	}
	d := pyde.NewDecoder(b)
	return d.String()
}

// Set writes the "token_symbol" scalar.
func (__stateTokenSymbol) Set(v string) {
	e := pyde.NewEncoder()
	e.String(v)
	pyde.StoreScalar("token_symbol", e.Finish())
}

type __stateTotalSupply struct{}

// Get reads the "total_supply" scalar, returning the zero value if unset.
func (__stateTotalSupply) Get() uint64 {
	b, ok := pyde.LoadScalar("total_supply")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "total_supply" scalar.
func (__stateTotalSupply) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("total_supply", e.Finish())
}

type __stateMaxSupply struct{}

// Get reads the "max_supply" scalar, returning the zero value if unset.
func (__stateMaxSupply) Get() uint64 {
	b, ok := pyde.LoadScalar("max_supply")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "max_supply" scalar.
func (__stateMaxSupply) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("max_supply", e.Finish())
}

type __stateNextId struct{}

// Get reads the "next_id" scalar, returning the zero value if unset.
func (__stateNextId) Get() uint64 {
	b, ok := pyde.LoadScalar("next_id")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "next_id" scalar.
func (__stateNextId) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("next_id", e.Finish())
}

type __stateMinter struct{}

// Get reads the "minter" scalar, returning the zero value if unset.
func (__stateMinter) Get() pyde.Address {
	b, ok := pyde.LoadScalar("minter")
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes the "minter" scalar.
func (__stateMinter) Set(v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreScalar("minter", e.Finish())
}

type __stateManager struct{}

// Get reads the "manager" scalar, returning the zero value if unset.
func (__stateManager) Get() pyde.Address {
	b, ok := pyde.LoadScalar("manager")
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes the "manager" scalar.
func (__stateManager) Set(v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreScalar("manager", e.Finish())
}

type __stateOwners struct{}

// Get reads "owners"[keys], returning the zero value if unset.
func (__stateOwners) Get(k0 uint64) pyde.Address {
	b, ok := pyde.LoadMap1("owners", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes "owners"[keys] = v.
func (__stateOwners) Set(k0 uint64, v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreMap1("owners", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "owners"[keys].
func (__stateOwners) Delete(k0 uint64) {
	pyde.DeleteMap1("owners", pyde.NewEncoder().U64(k0).Finish())
}

type __stateBalances struct{}

// Get reads "balances"[keys], returning the zero value if unset.
func (__stateBalances) Get(k0 pyde.Address) uint64 {
	b, ok := pyde.LoadMap1("balances", pyde.NewEncoder().Address(k0).Finish())
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes "balances"[keys] = v.
func (__stateBalances) Set(k0 pyde.Address, v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreMap1("balances", pyde.NewEncoder().Address(k0).Finish(), e.Finish())
}

// Delete clears "balances"[keys].
func (__stateBalances) Delete(k0 pyde.Address) {
	pyde.DeleteMap1("balances", pyde.NewEncoder().Address(k0).Finish())
}

type __stateTokenApprovals struct{}

// Get reads "token_approvals"[keys], returning the zero value if unset.
func (__stateTokenApprovals) Get(k0 uint64) pyde.Address {
	b, ok := pyde.LoadMap1("token_approvals", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes "token_approvals"[keys] = v.
func (__stateTokenApprovals) Set(k0 uint64, v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreMap1("token_approvals", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "token_approvals"[keys].
func (__stateTokenApprovals) Delete(k0 uint64) {
	pyde.DeleteMap1("token_approvals", pyde.NewEncoder().U64(k0).Finish())
}

type __stateOperatorApprovals struct{}

// Get reads "operator_approvals"[keys], returning the zero value if unset.
func (__stateOperatorApprovals) Get(k0 pyde.Address, k1 pyde.Address) bool {
	b, ok := pyde.LoadMap2("operator_approvals", pyde.NewEncoder().Address(k0).Finish(), pyde.NewEncoder().Address(k1).Finish())
	if !ok {
		return false
	}
	d := pyde.NewDecoder(b)
	return d.Bool()
}

// Set writes "operator_approvals"[keys] = v.
func (__stateOperatorApprovals) Set(k0 pyde.Address, k1 pyde.Address, v bool) {
	e := pyde.NewEncoder()
	e.Bool(v)
	pyde.StoreMap2("operator_approvals", pyde.NewEncoder().Address(k0).Finish(), pyde.NewEncoder().Address(k1).Finish(), e.Finish())
}

// Delete clears "operator_approvals"[keys].
func (__stateOperatorApprovals) Delete(k0 pyde.Address, k1 pyde.Address) {
	pyde.DeleteMap2("operator_approvals", pyde.NewEncoder().Address(k0).Finish(), pyde.NewEncoder().Address(k1).Finish())
}

type __stateTokenUris struct{}

// Get reads "token_uris"[keys], returning the zero value if unset.
func (__stateTokenUris) Get(k0 uint64) string {
	b, ok := pyde.LoadMap1("token_uris", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return ""
	}
	d := pyde.NewDecoder(b)
	return d.String()
}

// Set writes "token_uris"[keys] = v.
func (__stateTokenUris) Set(k0 uint64, v string) {
	e := pyde.NewEncoder()
	e.String(v)
	pyde.StoreMap1("token_uris", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "token_uris"[keys].
func (__stateTokenUris) Delete(k0 uint64) {
	pyde.DeleteMap1("token_uris", pyde.NewEncoder().U64(k0).Finish())
}

// ── Events ─────────────────────────────────────────────────────────

// __scalarTopic packs a fixed-width scalar's little-endian bytes into a
// 32-byte topic, right-padded with zeros — the engine's convention for an
// indexed primitive (matches Rust's declare_events! topic layout).
func __scalarTopic(le []byte) pyde.Bytes32 {
	var t pyde.Bytes32
	copy(t[:], le)
	return t
}

// Approval is the Approval(address,address,uint64) event. Emit it with a named-field
// literal: Approval{...}.Emit().
type Approval struct {
	Owner    pyde.Address
	Approved pyde.Address
	TokenId  uint64
}

// Emit appends this Approval event to the receipt.
func (ev Approval) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Approval(address,address,uint64)"),
		pyde.Bytes32(ev.Owner),
		pyde.Bytes32(ev.Approved),
		__scalarTopic(pyde.NewEncoder().U64(ev.TokenId).Finish()),
	}
	pyde.Emit(topics, nil)
}

// ApprovalForAll is the ApprovalForAll(address,address,bool) event. Emit it with a named-field
// literal: ApprovalForAll{...}.Emit().
type ApprovalForAll struct {
	Owner    pyde.Address
	Operator pyde.Address
	Approved bool
}

// Emit appends this ApprovalForAll event to the receipt.
func (ev ApprovalForAll) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("ApprovalForAll(address,address,bool)"),
		pyde.Bytes32(ev.Owner),
		pyde.Bytes32(ev.Operator),
	}
	e := pyde.NewEncoder()
	e.Bool(ev.Approved)
	pyde.Emit(topics, e.Finish())
}

// RoleTransfer is the RoleTransfer(bytes32,address,address) event. Emit it with a named-field
// literal: RoleTransfer{...}.Emit().
type RoleTransfer struct {
	Role     pyde.Bytes32
	Holder   pyde.Address
	Previous pyde.Address
}

// Emit appends this RoleTransfer event to the receipt.
func (ev RoleTransfer) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("RoleTransfer(bytes32,address,address)"),
		pyde.Bytes32(ev.Role),
		pyde.Bytes32(ev.Holder),
	}
	e := pyde.NewEncoder()
	e.Address(ev.Previous)
	pyde.Emit(topics, e.Finish())
}

// Transfer is the Transfer(address,address,uint64) event. Emit it with a named-field
// literal: Transfer{...}.Emit().
type Transfer struct {
	From    pyde.Address
	To      pyde.Address
	TokenId uint64
}

// Emit appends this Transfer event to the receipt.
func (ev Transfer) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Transfer(address,address,uint64)"),
		pyde.Bytes32(ev.From),
		pyde.Bytes32(ev.To),
		__scalarTopic(pyde.NewEncoder().U64(ev.TokenId).Finish()),
	}
	pyde.Emit(topics, nil)
}

// ── Dispatch ───────────────────────────────────────────────────────

//go:wasmexport approve
func __pyde_export_approve() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.U64()
	Approve(__a0, __a1)
	pyde.ReturnNothing()
}

//go:wasmexport balance_of
func __pyde_export_balance_of() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__r := BalanceOf(__a0)
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport burn
func __pyde_export_burn() {
	__d := pyde.Args()
	__a0 := __d.U64()
	Burn(__a0)
	pyde.ReturnNothing()
}

//go:wasmexport get_approved
func __pyde_export_get_approved() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__r := GetApproved(__a0)
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport init
func __pyde_export_init() {
	__d := pyde.Args()
	__a0 := __d.String()
	__a1 := __d.String()
	__a2 := __d.U64()
	Init(__a0, __a1, __a2)
	pyde.ReturnNothing()
}

//go:wasmexport is_approved_for_all
func __pyde_export_is_approved_for_all() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.Address()
	__r := IsApprovedForAll(__a0, __a1)
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport manager
func __pyde_export_manager() {
	__r := Manager()
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport max_supply
func __pyde_export_max_supply() {
	__r := MaxSupply()
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport mint
func __pyde_export_mint() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.String()
	__r := Mint(__a0, __a1)
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport minter
func __pyde_export_minter() {
	__r := Minter()
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport name
func __pyde_export_name() {
	__r := Name()
	__e := pyde.NewEncoder()
	__e.String(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport owner_of
func __pyde_export_owner_of() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__r := OwnerOf(__a0)
	__e := pyde.NewEncoder()
	__e.Address(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport set_approval_for_all
func __pyde_export_set_approval_for_all() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.Bool()
	SetApprovalForAll(__a0, __a1)
	pyde.ReturnNothing()
}

//go:wasmexport set_manager
func __pyde_export_set_manager() {
	__d := pyde.Args()
	__a0 := __d.Address()
	SetManager(__a0)
	pyde.ReturnNothing()
}

//go:wasmexport set_minter
func __pyde_export_set_minter() {
	__d := pyde.Args()
	__a0 := __d.Address()
	SetMinter(__a0)
	pyde.ReturnNothing()
}

//go:wasmexport standard
func __pyde_export_standard() {
	__r := Standard()
	__e := pyde.NewEncoder()
	__e.String(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport symbol
func __pyde_export_symbol() {
	__r := Symbol()
	__e := pyde.NewEncoder()
	__e.String(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport token_uri
func __pyde_export_token_uri() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__r := TokenUri(__a0)
	__e := pyde.NewEncoder()
	__e.String(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport total_supply
func __pyde_export_total_supply() {
	__r := TotalSupply()
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport transfer_call
func __pyde_export_transfer_call() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.U64()
	__a2 := __decodeVecU8(__d)
	__r := TransferCall(__a0, __a1, __a2)
	__e := pyde.NewEncoder()
	__e.U32(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport transfer_from
func __pyde_export_transfer_from() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.Address()
	__a2 := __d.U64()
	TransferFrom(__a0, __a1, __a2)
	pyde.ReturnNothing()
}
