// Code generated by otigen. DO NOT EDIT.
//
// Wires this contract's otigen.toml to the Pyde host ABI:
// //go:wasmexport dispatch + typed State accessors. Regenerated
// on every `otigen build`.

//go:build tinygo

package main

import pyde "github.com/pyde-net/pyde-host/go"

var _ = pyde.StatusOK

// ── Vec codecs ─────────────────────────────────────────────────────

func __encodeVecAddress(e *pyde.Encoder, v []pyde.Address) {
	e.U32(uint32(len(v)))
	for _, x := range v {
		e.Address(x)
	}
}

func __decodeVecAddress(d *pyde.Decoder) []pyde.Address {
	n := int(d.U32())
	out := make([]pyde.Address, n)
	for i := range out {
		out[i] = d.Address()
	}
	return out
}

// ── State ──────────────────────────────────────────────────────────

// State is the typed view of this contract's [state] schema.
var State = struct {
	VotingPeriodSecs            __stateVotingPeriodSecs
	QuorumPercent               __stateQuorumPercent
	MemberCount                 __stateMemberCount
	ProposalCount               __stateProposalCount
	Members                     __stateMembers
	JoinedAt                    __stateJoinedAt
	ProposalTarget              __stateProposalTarget
	ProposalFunction            __stateProposalFunction
	ProposalCalldata            __stateProposalCalldata
	ProposalProposer            __stateProposalProposer
	ProposalCreated             __stateProposalCreated
	ProposalYes                 __stateProposalYes
	ProposalNo                  __stateProposalNo
	ProposalExecuted            __stateProposalExecuted
	ProposalMemberCountSnapshot __stateProposalMemberCountSnapshot
	HasVoted                    __stateHasVoted
}{}

type __stateVotingPeriodSecs struct{}

// Get reads the "voting_period_secs" scalar, returning the zero value if unset.
func (__stateVotingPeriodSecs) Get() uint64 {
	b, ok := pyde.LoadScalar("voting_period_secs")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "voting_period_secs" scalar.
func (__stateVotingPeriodSecs) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("voting_period_secs", e.Finish())
}

type __stateQuorumPercent struct{}

// Get reads the "quorum_percent" scalar, returning the zero value if unset.
func (__stateQuorumPercent) Get() uint64 {
	b, ok := pyde.LoadScalar("quorum_percent")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "quorum_percent" scalar.
func (__stateQuorumPercent) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("quorum_percent", e.Finish())
}

type __stateMemberCount struct{}

// Get reads the "member_count" scalar, returning the zero value if unset.
func (__stateMemberCount) Get() uint64 {
	b, ok := pyde.LoadScalar("member_count")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "member_count" scalar.
func (__stateMemberCount) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("member_count", e.Finish())
}

type __stateProposalCount struct{}

// Get reads the "proposal_count" scalar, returning the zero value if unset.
func (__stateProposalCount) Get() uint64 {
	b, ok := pyde.LoadScalar("proposal_count")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "proposal_count" scalar.
func (__stateProposalCount) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("proposal_count", e.Finish())
}

type __stateMembers struct{}

// Get reads "members"[keys], returning the zero value if unset.
func (__stateMembers) Get(k0 pyde.Address) bool {
	b, ok := pyde.LoadMap1("members", pyde.NewEncoder().Address(k0).Finish())
	if !ok {
		return false
	}
	d := pyde.NewDecoder(b)
	return d.Bool()
}

// Set writes "members"[keys] = v.
func (__stateMembers) Set(k0 pyde.Address, v bool) {
	e := pyde.NewEncoder()
	e.Bool(v)
	pyde.StoreMap1("members", pyde.NewEncoder().Address(k0).Finish(), e.Finish())
}

// Delete clears "members"[keys].
func (__stateMembers) Delete(k0 pyde.Address) {
	pyde.DeleteMap1("members", pyde.NewEncoder().Address(k0).Finish())
}

type __stateJoinedAt struct{}

// Get reads "joined_at"[keys], returning the zero value if unset.
func (__stateJoinedAt) Get(k0 pyde.Address) uint64 {
	b, ok := pyde.LoadMap1("joined_at", pyde.NewEncoder().Address(k0).Finish())
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes "joined_at"[keys] = v.
func (__stateJoinedAt) Set(k0 pyde.Address, v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreMap1("joined_at", pyde.NewEncoder().Address(k0).Finish(), e.Finish())
}

// Delete clears "joined_at"[keys].
func (__stateJoinedAt) Delete(k0 pyde.Address) {
	pyde.DeleteMap1("joined_at", pyde.NewEncoder().Address(k0).Finish())
}

type __stateProposalTarget struct{}

// Get reads "proposal_target"[keys], returning the zero value if unset.
func (__stateProposalTarget) Get(k0 uint64) pyde.Address {
	b, ok := pyde.LoadMap1("proposal_target", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes "proposal_target"[keys] = v.
func (__stateProposalTarget) Set(k0 uint64, v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreMap1("proposal_target", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "proposal_target"[keys].
func (__stateProposalTarget) Delete(k0 uint64) {
	pyde.DeleteMap1("proposal_target", pyde.NewEncoder().U64(k0).Finish())
}

type __stateProposalFunction struct{}

// Get reads "proposal_function"[keys], returning the zero value if unset.
func (__stateProposalFunction) Get(k0 uint64) string {
	b, ok := pyde.LoadMap1("proposal_function", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return ""
	}
	d := pyde.NewDecoder(b)
	return d.String()
}

// Set writes "proposal_function"[keys] = v.
func (__stateProposalFunction) Set(k0 uint64, v string) {
	e := pyde.NewEncoder()
	e.String(v)
	pyde.StoreMap1("proposal_function", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "proposal_function"[keys].
func (__stateProposalFunction) Delete(k0 uint64) {
	pyde.DeleteMap1("proposal_function", pyde.NewEncoder().U64(k0).Finish())
}

type __stateProposalCalldata struct{}

// Get reads "proposal_calldata"[keys], returning the zero value if unset.
func (__stateProposalCalldata) Get(k0 uint64) []byte {
	b, ok := pyde.LoadMap1("proposal_calldata", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return nil
	}
	d := pyde.NewDecoder(b)
	return d.Bytes()
}

// Set writes "proposal_calldata"[keys] = v.
func (__stateProposalCalldata) Set(k0 uint64, v []byte) {
	e := pyde.NewEncoder()
	e.Bytes(v)
	pyde.StoreMap1("proposal_calldata", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "proposal_calldata"[keys].
func (__stateProposalCalldata) Delete(k0 uint64) {
	pyde.DeleteMap1("proposal_calldata", pyde.NewEncoder().U64(k0).Finish())
}

type __stateProposalProposer struct{}

// Get reads "proposal_proposer"[keys], returning the zero value if unset.
func (__stateProposalProposer) Get(k0 uint64) pyde.Address {
	b, ok := pyde.LoadMap1("proposal_proposer", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return pyde.Address{}
	}
	d := pyde.NewDecoder(b)
	return d.Address()
}

// Set writes "proposal_proposer"[keys] = v.
func (__stateProposalProposer) Set(k0 uint64, v pyde.Address) {
	e := pyde.NewEncoder()
	e.Address(v)
	pyde.StoreMap1("proposal_proposer", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "proposal_proposer"[keys].
func (__stateProposalProposer) Delete(k0 uint64) {
	pyde.DeleteMap1("proposal_proposer", pyde.NewEncoder().U64(k0).Finish())
}

type __stateProposalCreated struct{}

// Get reads "proposal_created"[keys], returning the zero value if unset.
func (__stateProposalCreated) Get(k0 uint64) uint64 {
	b, ok := pyde.LoadMap1("proposal_created", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes "proposal_created"[keys] = v.
func (__stateProposalCreated) Set(k0 uint64, v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreMap1("proposal_created", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "proposal_created"[keys].
func (__stateProposalCreated) Delete(k0 uint64) {
	pyde.DeleteMap1("proposal_created", pyde.NewEncoder().U64(k0).Finish())
}

type __stateProposalYes struct{}

// Get reads "proposal_yes"[keys], returning the zero value if unset.
func (__stateProposalYes) Get(k0 uint64) uint64 {
	b, ok := pyde.LoadMap1("proposal_yes", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes "proposal_yes"[keys] = v.
func (__stateProposalYes) Set(k0 uint64, v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreMap1("proposal_yes", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "proposal_yes"[keys].
func (__stateProposalYes) Delete(k0 uint64) {
	pyde.DeleteMap1("proposal_yes", pyde.NewEncoder().U64(k0).Finish())
}

type __stateProposalNo struct{}

// Get reads "proposal_no"[keys], returning the zero value if unset.
func (__stateProposalNo) Get(k0 uint64) uint64 {
	b, ok := pyde.LoadMap1("proposal_no", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes "proposal_no"[keys] = v.
func (__stateProposalNo) Set(k0 uint64, v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreMap1("proposal_no", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "proposal_no"[keys].
func (__stateProposalNo) Delete(k0 uint64) {
	pyde.DeleteMap1("proposal_no", pyde.NewEncoder().U64(k0).Finish())
}

type __stateProposalExecuted struct{}

// Get reads "proposal_executed"[keys], returning the zero value if unset.
func (__stateProposalExecuted) Get(k0 uint64) bool {
	b, ok := pyde.LoadMap1("proposal_executed", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return false
	}
	d := pyde.NewDecoder(b)
	return d.Bool()
}

// Set writes "proposal_executed"[keys] = v.
func (__stateProposalExecuted) Set(k0 uint64, v bool) {
	e := pyde.NewEncoder()
	e.Bool(v)
	pyde.StoreMap1("proposal_executed", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "proposal_executed"[keys].
func (__stateProposalExecuted) Delete(k0 uint64) {
	pyde.DeleteMap1("proposal_executed", pyde.NewEncoder().U64(k0).Finish())
}

type __stateProposalMemberCountSnapshot struct{}

// Get reads "proposal_member_count_snapshot"[keys], returning the zero value if unset.
func (__stateProposalMemberCountSnapshot) Get(k0 uint64) uint64 {
	b, ok := pyde.LoadMap1("proposal_member_count_snapshot", pyde.NewEncoder().U64(k0).Finish())
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes "proposal_member_count_snapshot"[keys] = v.
func (__stateProposalMemberCountSnapshot) Set(k0 uint64, v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreMap1("proposal_member_count_snapshot", pyde.NewEncoder().U64(k0).Finish(), e.Finish())
}

// Delete clears "proposal_member_count_snapshot"[keys].
func (__stateProposalMemberCountSnapshot) Delete(k0 uint64) {
	pyde.DeleteMap1("proposal_member_count_snapshot", pyde.NewEncoder().U64(k0).Finish())
}

type __stateHasVoted struct{}

// Get reads "has_voted"[keys], returning the zero value if unset.
func (__stateHasVoted) Get(k0 uint64, k1 pyde.Address) bool {
	b, ok := pyde.LoadMap2("has_voted", pyde.NewEncoder().U64(k0).Finish(), pyde.NewEncoder().Address(k1).Finish())
	if !ok {
		return false
	}
	d := pyde.NewDecoder(b)
	return d.Bool()
}

// Set writes "has_voted"[keys] = v.
func (__stateHasVoted) Set(k0 uint64, k1 pyde.Address, v bool) {
	e := pyde.NewEncoder()
	e.Bool(v)
	pyde.StoreMap2("has_voted", pyde.NewEncoder().U64(k0).Finish(), pyde.NewEncoder().Address(k1).Finish(), e.Finish())
}

// Delete clears "has_voted"[keys].
func (__stateHasVoted) Delete(k0 uint64, k1 pyde.Address) {
	pyde.DeleteMap2("has_voted", pyde.NewEncoder().U64(k0).Finish(), pyde.NewEncoder().Address(k1).Finish())
}

// ── Events ─────────────────────────────────────────────────────────

// __scalarTopic packs a fixed-width scalar's little-endian bytes into a
// 32-byte topic, right-padded with zeros — the engine's convention for an
// indexed primitive (matches Rust's declare_events! topic layout).
func __scalarTopic(le []byte) pyde.Bytes32 {
	var t pyde.Bytes32
	copy(t[:], le)
	return t
}

// MemberAdded is the MemberAdded(address) event. Emit it with a named-field
// literal: MemberAdded{...}.Emit().
type MemberAdded struct {
	Member pyde.Address
}

// Emit appends this MemberAdded event to the receipt.
func (ev MemberAdded) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("MemberAdded(address)"),
		pyde.Bytes32(ev.Member),
	}
	pyde.Emit(topics, nil)
}

// MemberRemoved is the MemberRemoved(address) event. Emit it with a named-field
// literal: MemberRemoved{...}.Emit().
type MemberRemoved struct {
	Member pyde.Address
}

// Emit appends this MemberRemoved event to the receipt.
func (ev MemberRemoved) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("MemberRemoved(address)"),
		pyde.Bytes32(ev.Member),
	}
	pyde.Emit(topics, nil)
}

// ProposalCreated is the ProposalCreated(uint64,address,address) event. Emit it with a named-field
// literal: ProposalCreated{...}.Emit().
type ProposalCreated struct {
	ProposalId uint64
	Proposer   pyde.Address
	Target     pyde.Address
}

// Emit appends this ProposalCreated event to the receipt.
func (ev ProposalCreated) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("ProposalCreated(uint64,address,address)"),
		__scalarTopic(pyde.NewEncoder().U64(ev.ProposalId).Finish()),
		pyde.Bytes32(ev.Proposer),
		pyde.Bytes32(ev.Target),
	}
	pyde.Emit(topics, nil)
}

// ProposalExecuted is the ProposalExecuted(uint64,bool) event. Emit it with a named-field
// literal: ProposalExecuted{...}.Emit().
type ProposalExecuted struct {
	ProposalId uint64
	Success    bool
}

// Emit appends this ProposalExecuted event to the receipt.
func (ev ProposalExecuted) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("ProposalExecuted(uint64,bool)"),
		__scalarTopic(pyde.NewEncoder().U64(ev.ProposalId).Finish()),
	}
	e := pyde.NewEncoder()
	e.Bool(ev.Success)
	pyde.Emit(topics, e.Finish())
}

// Voted is the Voted(uint64,address,bool) event. Emit it with a named-field
// literal: Voted{...}.Emit().
type Voted struct {
	ProposalId uint64
	Voter      pyde.Address
	Support    bool
}

// Emit appends this Voted event to the receipt.
func (ev Voted) Emit() {
	topics := []pyde.Bytes32{
		pyde.EventTopic0("Voted(uint64,address,bool)"),
		__scalarTopic(pyde.NewEncoder().U64(ev.ProposalId).Finish()),
		pyde.Bytes32(ev.Voter),
	}
	e := pyde.NewEncoder()
	e.Bool(ev.Support)
	pyde.Emit(topics, e.Finish())
}

// ── Dispatch ───────────────────────────────────────────────────────

//go:wasmexport add_member
func __pyde_export_add_member() {
	__d := pyde.Args()
	__a0 := __d.Address()
	AddMember(__a0)
	pyde.ReturnNothing()
}

//go:wasmexport execute_proposal
func __pyde_export_execute_proposal() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__r := ExecuteProposal(__a0)
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport get_proposal_executed
func __pyde_export_get_proposal_executed() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__r := GetProposalExecuted(__a0)
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport get_proposal_no
func __pyde_export_get_proposal_no() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__r := GetProposalNo(__a0)
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport get_proposal_yes
func __pyde_export_get_proposal_yes() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__r := GetProposalYes(__a0)
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport has_voted_on
func __pyde_export_has_voted_on() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__a1 := __d.Address()
	__r := HasVotedOn(__a0, __a1)
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport init
func __pyde_export_init() {
	__d := pyde.Args()
	__a0 := __decodeVecAddress(__d)
	__a1 := __d.U64()
	__a2 := __d.U64()
	Init(__a0, __a1, __a2)
	pyde.ReturnNothing()
}

//go:wasmexport is_member
func __pyde_export_is_member() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__r := IsMember(__a0)
	__e := pyde.NewEncoder()
	__e.Bool(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport member_count
func __pyde_export_member_count() {
	__r := MemberCount()
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport proposal_count
func __pyde_export_proposal_count() {
	__r := ProposalCount()
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport propose
func __pyde_export_propose() {
	__d := pyde.Args()
	__a0 := __d.Address()
	__a1 := __d.String()
	__a2 := __d.Bytes()
	__r := Propose(__a0, __a1, __a2)
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport remove_member
func __pyde_export_remove_member() {
	__d := pyde.Args()
	__a0 := __d.Address()
	RemoveMember(__a0)
	pyde.ReturnNothing()
}

//go:wasmexport vote
func __pyde_export_vote() {
	__d := pyde.Args()
	__a0 := __d.U64()
	__a1 := __d.Bool()
	Vote(__a0, __a1)
	pyde.ReturnNothing()
}

//go:wasmexport voting_period_secs
func __pyde_export_voting_period_secs() {
	__r := VotingPeriodSecs()
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}
