// Code generated by otigen. DO NOT EDIT.
//
// Wires this contract's otigen.toml to the Pyde host ABI: a self-contained
// borsh runtime + typed storage accessors, event emitters, and () -> ()
// entry-dispatch shims. Your main.c #includes this header and defines the
// __<fn>_impl bodies it forward-declares. Regenerated on every `otigen build`.

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <pyde/host.h>  // -Iinclude resolves this to include/pyde/host.h

// ── bump allocator ───────────────────────────────────────────────────
//
// wasm-ld synthesizes __heap_base at the end of static data. A contract call
// is single-shot (execute, then the instance is torn down), so allocation is
// bump-only with no free. Grows linear memory on demand.
extern uint8_t __heap_base;
static uint32_t __pyde_hp = 0;

static void *__pyde_alloc(uint32_t n) {
    if (__pyde_hp == 0) {
        __pyde_hp = (uint32_t)(uintptr_t)&__heap_base;
    }
    n = (n + 7u) & ~7u; // 8-byte align (holds __uint128_t)
    uint32_t p = __pyde_hp;
    uint32_t end = p + n;
    uint32_t cur = (uint32_t)__builtin_wasm_memory_size(0) * 65536u;
    if (end > cur) {
        uint32_t pages = ((end - cur) + 65535u) / 65536u;
        if (__builtin_wasm_memory_grow(0, (uintptr_t)pages) == (uintptr_t)-1) {
            revert((const uint8_t *)"pyde: out of memory", 19);
        }
    }
    __pyde_hp = end;
    return (void *)(uintptr_t)p;
}

static void __pyde_memcpy(uint8_t *d, const uint8_t *s, uint32_t n) {
    for (uint32_t i = 0; i < n; i++) {
        d[i] = s[i];
    }
}

// ── 128-bit arithmetic runtime (freestanding / -nostdlib) ─────────────
//
// Multiplying or dividing __uint128_t/__int128_t lowers to compiler-rt
// builtins (__multi3 / __udivti3 / __umodti3) that -nostdlib does not link.
// These freestanding implementations provide them, so a contract's u128 math
// "just works" — the C analogue of the u128 arithmetic Rust/Go get from their
// standard libraries. External linkage (not static) so clang's generated calls
// resolve and there's no unused-function warning when a contract doesn't need
// them; -flto strips them when unused, -fvisibility=hidden keeps them unexported.
void __pyde_mul64(uint64_t a, uint64_t b, uint64_t *hi, uint64_t *lo) {
    uint64_t a0 = a & 0xffffffffu, a1 = a >> 32;
    uint64_t b0 = b & 0xffffffffu, b1 = b >> 32;
    uint64_t ll = a0 * b0, lh = a0 * b1, hl = a1 * b0, hh = a1 * b1;
    uint64_t cross = (ll >> 32) + (lh & 0xffffffffu) + (hl & 0xffffffffu);
    *lo = (ll & 0xffffffffu) | (cross << 32);
    *hi = hh + (lh >> 32) + (hl >> 32) + (cross >> 32);
}
// Low 128 bits of a 128x128 multiply (identical for signed/unsigned).
__int128 __multi3(__int128 a, __int128 b) {
    unsigned __int128 ua = (unsigned __int128)a, ub = (unsigned __int128)b;
    uint64_t al = (uint64_t)ua, ah = (uint64_t)(ua >> 64);
    uint64_t bl = (uint64_t)ub, bh = (uint64_t)(ub >> 64);
    uint64_t phi, plo;
    __pyde_mul64(al, bl, &phi, &plo);
    uint64_t mid = al * bh + ah * bl;
    unsigned __int128 r = ((unsigned __int128)(phi + mid) << 64) | plo;
    return (__int128)r;
}
// Unsigned 128-bit divide / remainder via shift-and-subtract. Every shift is a
// CONSTANT count (1 or 127) so it never recurses into __ashlti3/__lshrti3.
unsigned __int128 __udivti3(unsigned __int128 n, unsigned __int128 d) {
    if (d == 0) { __builtin_trap(); }
    unsigned __int128 q = 0, r = 0;
    for (int i = 0; i < 128; i++) {
        r = (r << 1) | (n >> 127);
        n <<= 1;
        q <<= 1;
        if (r >= d) { r -= d; q |= 1; }
    }
    return q;
}
unsigned __int128 __umodti3(unsigned __int128 n, unsigned __int128 d) {
    if (d == 0) { __builtin_trap(); }
    unsigned __int128 r = 0;
    for (int i = 0; i < 128; i++) {
        r = (r << 1) | (n >> 127);
        n <<= 1;
        if (r >= d) { r -= d; }
    }
    return r;
}

// ── value types ──────────────────────────────────────────────────────
typedef struct { uint8_t bytes[32]; } pyde_address;
typedef struct { uint8_t bytes[32]; } pyde_bytes32;
typedef struct { uint8_t *ptr; uint32_t len; } pyde_bytes;
typedef struct { uint8_t *ptr; uint32_t len; } pyde_string;

// ── borsh encoder (growable, bump-backed) ────────────────────────────
typedef struct { uint8_t *buf; uint32_t len; uint32_t cap; } pyde_enc;

static pyde_enc pyde_enc_new(void) {
    pyde_enc e;
    e.cap = 64;
    e.buf = (uint8_t *)__pyde_alloc(e.cap);
    e.len = 0;
    return e;
}
static void __pyde_enc_reserve(pyde_enc *e, uint32_t extra) {
    if (e->len + extra <= e->cap) {
        return;
    }
    uint32_t nc = e->cap * 2u;
    while (nc < e->len + extra) {
        nc *= 2u;
    }
    uint8_t *nb = (uint8_t *)__pyde_alloc(nc);
    __pyde_memcpy(nb, e->buf, e->len);
    e->buf = nb;
    e->cap = nc;
}
// u8 is a single byte with no shift — kept separate so the macro below never
// emits a `>> 8` on an 8-bit type (statically flagged by -Wshift-count-overflow
// even when guarded). u16..u128 only ever shift by 8, always < their width.
static void pyde_enc_u8(pyde_enc *e, uint8_t v) {
    __pyde_enc_reserve(e, 1);
    e->buf[e->len++] = v;
}
#define PYDE_ENC_UINT(SFX, TY, WIDTH)                                          \
    static void pyde_enc_##SFX(pyde_enc *e, TY v) {                            \
        __pyde_enc_reserve(e, WIDTH);                                          \
        for (int __i = 0; __i < WIDTH; __i++) {                                \
            e->buf[e->len++] = (uint8_t)(v & 0xff);                            \
            v >>= 8;                                                           \
        }                                                                      \
    }
PYDE_ENC_UINT(u16, uint16_t, 2)
PYDE_ENC_UINT(u32, uint32_t, 4)
PYDE_ENC_UINT(u64, uint64_t, 8)
PYDE_ENC_UINT(u128, __uint128_t, 16)
// signed integers encode with identical bytes (two's-complement LE).
static void pyde_enc_i8(pyde_enc *e, int8_t v) { pyde_enc_u8(e, (uint8_t)v); }
static void pyde_enc_i16(pyde_enc *e, int16_t v) { pyde_enc_u16(e, (uint16_t)v); }
static void pyde_enc_i32(pyde_enc *e, int32_t v) { pyde_enc_u32(e, (uint32_t)v); }
static void pyde_enc_i64(pyde_enc *e, int64_t v) { pyde_enc_u64(e, (uint64_t)v); }
static void pyde_enc_i128(pyde_enc *e, __int128_t v) { pyde_enc_u128(e, (__uint128_t)v); }
static void pyde_enc_bool(pyde_enc *e, bool v) { pyde_enc_u8(e, v ? 1u : 0u); }
static void pyde_enc_address(pyde_enc *e, pyde_address v) {
    __pyde_enc_reserve(e, 32);
    __pyde_memcpy(e->buf + e->len, v.bytes, 32);
    e->len += 32;
}
static void pyde_enc_bytes32(pyde_enc *e, pyde_bytes32 v) {
    __pyde_enc_reserve(e, 32);
    __pyde_memcpy(e->buf + e->len, v.bytes, 32);
    e->len += 32;
}
static void pyde_enc_bytes(pyde_enc *e, pyde_bytes v) {
    pyde_enc_u32(e, v.len);
    __pyde_enc_reserve(e, v.len);
    __pyde_memcpy(e->buf + e->len, v.ptr, v.len);
    e->len += v.len;
}
static void pyde_enc_string(pyde_enc *e, pyde_string v) {
    pyde_enc_u32(e, v.len);
    __pyde_enc_reserve(e, v.len);
    __pyde_memcpy(e->buf + e->len, v.ptr, v.len);
    e->len += v.len;
}
static pyde_bytes pyde_enc_finish(pyde_enc *e) {
    pyde_bytes b;
    b.ptr = e->buf;
    b.len = e->len;
    return b;
}

// ── borsh decoder ────────────────────────────────────────────────────
typedef struct { const uint8_t *buf; uint32_t len; uint32_t pos; } pyde_dec;

static pyde_dec pyde_dec_new(const uint8_t *buf, uint32_t len) {
    pyde_dec d;
    d.buf = buf;
    d.len = len;
    d.pos = 0;
    return d;
}
static void __pyde_dec_need(pyde_dec *d, uint32_t n) {
    if (d->pos + n > d->len) {
        revert((const uint8_t *)"pyde: borsh underrun", 20);
    }
}
#define PYDE_DEC_UINT(SFX, TY, WIDTH)                                          \
    static TY pyde_dec_##SFX(pyde_dec *d) {                                    \
        __pyde_dec_need(d, WIDTH);                                            \
        TY v = 0;                                                             \
        for (int __i = WIDTH - 1; __i >= 0; __i--) {                          \
            v = (TY)((v << 8) | (TY)d->buf[d->pos + (uint32_t)__i]);          \
        }                                                                     \
        d->pos += WIDTH;                                                     \
        return v;                                                             \
    }
PYDE_DEC_UINT(u8, uint8_t, 1)
PYDE_DEC_UINT(u16, uint16_t, 2)
PYDE_DEC_UINT(u32, uint32_t, 4)
PYDE_DEC_UINT(u64, uint64_t, 8)
PYDE_DEC_UINT(u128, __uint128_t, 16)
static int8_t pyde_dec_i8(pyde_dec *d) { return (int8_t)pyde_dec_u8(d); }
static int16_t pyde_dec_i16(pyde_dec *d) { return (int16_t)pyde_dec_u16(d); }
static int32_t pyde_dec_i32(pyde_dec *d) { return (int32_t)pyde_dec_u32(d); }
static int64_t pyde_dec_i64(pyde_dec *d) { return (int64_t)pyde_dec_u64(d); }
static __int128_t pyde_dec_i128(pyde_dec *d) { return (__int128_t)pyde_dec_u128(d); }
static bool pyde_dec_bool(pyde_dec *d) { return pyde_dec_u8(d) != 0u; }
static pyde_address pyde_dec_address(pyde_dec *d) {
    __pyde_dec_need(d, 32);
    pyde_address a;
    __pyde_memcpy(a.bytes, d->buf + d->pos, 32);
    d->pos += 32;
    return a;
}
static pyde_bytes32 pyde_dec_bytes32(pyde_dec *d) {
    __pyde_dec_need(d, 32);
    pyde_bytes32 a;
    __pyde_memcpy(a.bytes, d->buf + d->pos, 32);
    d->pos += 32;
    return a;
}
static pyde_bytes pyde_dec_bytes(pyde_dec *d) {
    uint32_t n = pyde_dec_u32(d);
    __pyde_dec_need(d, n);
    pyde_bytes b;
    b.len = n;
    b.ptr = (uint8_t *)__pyde_alloc(n == 0 ? 1u : n);
    __pyde_memcpy(b.ptr, d->buf + d->pos, n);
    d->pos += n;
    return b;
}
static pyde_string pyde_dec_string(pyde_dec *d) {
    pyde_bytes b = pyde_dec_bytes(d);
    pyde_string s;
    s.ptr = b.ptr;
    s.len = b.len;
    return s;
}

// ── calldata / return / context wrappers ─────────────────────────────
static pyde_dec pyde_args(void) {
    int32_t n = calldata_size();
    uint32_t len = n > 0 ? (uint32_t)n : 0u;
    uint8_t *buf = (uint8_t *)__pyde_alloc(len == 0 ? 1u : len);
    if (len > 0) {
        uint32_t cap = len;
        calldata_copy(buf, &cap);
        len = cap;
    }
    return pyde_dec_new(buf, len);
}
static void pyde_return_bytes(pyde_bytes b) { pyde_return(b.ptr, (int32_t)b.len); }
static void pyde_return_nothing(void) { pyde_return((const uint8_t *)0, 0); }
static pyde_address pyde_caller(void) {
    pyde_address a;
    caller(a.bytes);
    return a;
}
static pyde_address pyde_self(void) {
    pyde_address a;
    self_address(a.bytes);
    return a;
}
static bool pyde_addr_eq(pyde_address a, pyde_address b) {
    for (int i = 0; i < 32; i++) {
        if (a.bytes[i] != b.bytes[i]) {
            return false;
        }
    }
    return true;
}
// A string-literal revert: the length is computed at compile time from the
// literal's size, so there's no runtime strlen for clang's -O3 loop-idiom pass
// to rewrite into an (undefined) `strlen` call. For a dynamic message, call the
// host `revert(ptr, len)` directly.
#define pyde_revert_str(literal) revert((const uint8_t *)(literal), (int32_t)(sizeof(literal) - 1))

// ── typed storage wrappers (host derives the slot) ───────────────────
//
// The host derives Poseidon2(self_address || field || keys...) from the field
// NAME and (borsh-encoded) keys; the contract never hashes. Loads use the
// length-probe convention (out_max=0 → actual length), then a sized read into
// a bump buffer. A negative length means the slot was never written.
typedef struct { uint8_t *data; int32_t len; } pyde_loaded;

static pyde_loaded pyde_load_scalar_raw(const uint8_t *f, int32_t fl) {
    int32_t n = sload_scalar(f, fl, (uint8_t *)0, 0);
    pyde_loaded r;
    r.len = n;
    r.data = (uint8_t *)0;
    if (n > 0) {
        r.data = (uint8_t *)__pyde_alloc((uint32_t)n);
        sload_scalar(f, fl, r.data, n);
    }
    return r;
}
static void pyde_store_scalar_raw(const uint8_t *f, int32_t fl, pyde_bytes v) {
    sstore_scalar(f, fl, v.ptr, (int32_t)v.len);
}
static pyde_loaded pyde_load_map1_raw(const uint8_t *f, int32_t fl,
                                      const uint8_t *k, int32_t kl) {
    int32_t n = sload_map1(f, fl, k, kl, (uint8_t *)0, 0);
    pyde_loaded r;
    r.len = n;
    r.data = (uint8_t *)0;
    if (n > 0) {
        r.data = (uint8_t *)__pyde_alloc((uint32_t)n);
        sload_map1(f, fl, k, kl, r.data, n);
    }
    return r;
}
static void pyde_store_map1_raw(const uint8_t *f, int32_t fl,
                                const uint8_t *k, int32_t kl, pyde_bytes v) {
    sstore_map1(f, fl, k, kl, v.ptr, (int32_t)v.len);
}
static void pyde_delete_map1_raw(const uint8_t *f, int32_t fl,
                                 const uint8_t *k, int32_t kl) {
    sdelete_map1(f, fl, k, kl);
}
static pyde_loaded pyde_load_map2_raw(const uint8_t *f, int32_t fl,
                                      const uint8_t *k1, int32_t k1l,
                                      const uint8_t *k2, int32_t k2l) {
    int32_t n = sload_map2(f, fl, k1, k1l, k2, k2l, (uint8_t *)0, 0);
    pyde_loaded r;
    r.len = n;
    r.data = (uint8_t *)0;
    if (n > 0) {
        r.data = (uint8_t *)__pyde_alloc((uint32_t)n);
        sload_map2(f, fl, k1, k1l, k2, k2l, r.data, n);
    }
    return r;
}
static void pyde_store_map2_raw(const uint8_t *f, int32_t fl,
                                const uint8_t *k1, int32_t k1l,
                                const uint8_t *k2, int32_t k2l, pyde_bytes v) {
    sstore_map2(f, fl, k1, k1l, k2, k2l, v.ptr, (int32_t)v.len);
}
static void pyde_delete_map2_raw(const uint8_t *f, int32_t fl,
                                 const uint8_t *k1, int32_t k1l,
                                 const uint8_t *k2, int32_t k2l) {
    sdelete_map2(f, fl, k1, k1l, k2, k2l);
}
static pyde_loaded pyde_load_map3_raw(const uint8_t *f, int32_t fl,
                                      const uint8_t *k1, int32_t k1l,
                                      const uint8_t *k2, int32_t k2l,
                                      const uint8_t *k3, int32_t k3l) {
    int32_t n = sload_map3(f, fl, k1, k1l, k2, k2l, k3, k3l, (uint8_t *)0, 0);
    pyde_loaded r;
    r.len = n;
    r.data = (uint8_t *)0;
    if (n > 0) {
        r.data = (uint8_t *)__pyde_alloc((uint32_t)n);
        sload_map3(f, fl, k1, k1l, k2, k2l, k3, k3l, r.data, n);
    }
    return r;
}
static void pyde_store_map3_raw(const uint8_t *f, int32_t fl,
                                const uint8_t *k1, int32_t k1l,
                                const uint8_t *k2, int32_t k2l,
                                const uint8_t *k3, int32_t k3l, pyde_bytes v) {
    sstore_map3(f, fl, k1, k1l, k2, k2l, k3, k3l, v.ptr, (int32_t)v.len);
}
static void pyde_delete_map3_raw(const uint8_t *f, int32_t fl,
                                 const uint8_t *k1, int32_t k1l,
                                 const uint8_t *k2, int32_t k2l,
                                 const uint8_t *k3, int32_t k3l) {
    sdelete_map3(f, fl, k1, k1l, k2, k2l, k3, k3l);
}

// ── event topic packing ──────────────────────────────────────────────
//
// A fixed-width scalar topic is its little-endian borsh bytes, right-padded
// with zeros to 32 (matches Rust's declare_events! / go_gen __scalarTopic).
static void __pyde_scalar_topic(const uint8_t *le, uint32_t len, uint8_t out[32]) {
    for (int i = 0; i < 32; i++) {
        out[i] = 0;
    }
    __pyde_memcpy(out, le, len);
}

// ── Vec codecs ─────────────────────────────────────────────────────

typedef struct { uint8_t *ptr; uint32_t len; } pyde_vec_U8;
static void __encodeVecU8(pyde_enc *__e, pyde_vec_U8 __v) {
    pyde_enc_u32(__e, __v.len);
    for (uint32_t __i = 0; __i < __v.len; __i++) {
        pyde_enc_u8(__e, __v.ptr[__i]);
    }
}
static pyde_vec_U8 __decodeVecU8(pyde_dec *__d) {
    uint32_t __n = pyde_dec_u32(__d);
    pyde_vec_U8 __out;
    __out.len = __n;
    __out.ptr = (uint8_t *)__pyde_alloc((__n == 0 ? 1u : __n) * (uint32_t)sizeof(uint8_t));
    for (uint32_t __i = 0; __i < __n; __i++) {
        __out.ptr[__i] = pyde_dec_u8(__d);
    }
    return __out;
}

// ── State ──────────────────────────────────────────────────────────

// token_name_get reads the "token_name" scalar (zero if unset).
static pyde_string token_name_get(void) {
    pyde_loaded __l = pyde_load_scalar_raw((const uint8_t *)"token_name", 10);
    if (__l.len < 0) { return (pyde_string){0}; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_string(&__d);
}
// token_name_set writes the "token_name" scalar.
static void token_name_set(pyde_string __v) {
    pyde_enc __e = pyde_enc_new();
    pyde_enc_string(&__e, __v);
    pyde_store_scalar_raw((const uint8_t *)"token_name", 10, pyde_enc_finish(&__e));
}

// token_symbol_get reads the "token_symbol" scalar (zero if unset).
static pyde_string token_symbol_get(void) {
    pyde_loaded __l = pyde_load_scalar_raw((const uint8_t *)"token_symbol", 12);
    if (__l.len < 0) { return (pyde_string){0}; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_string(&__d);
}
// token_symbol_set writes the "token_symbol" scalar.
static void token_symbol_set(pyde_string __v) {
    pyde_enc __e = pyde_enc_new();
    pyde_enc_string(&__e, __v);
    pyde_store_scalar_raw((const uint8_t *)"token_symbol", 12, pyde_enc_finish(&__e));
}

// total_supply_get reads the "total_supply" scalar (zero if unset).
static uint64_t total_supply_get(void) {
    pyde_loaded __l = pyde_load_scalar_raw((const uint8_t *)"total_supply", 12);
    if (__l.len < 0) { return 0; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_u64(&__d);
}
// total_supply_set writes the "total_supply" scalar.
static void total_supply_set(uint64_t __v) {
    pyde_enc __e = pyde_enc_new();
    pyde_enc_u64(&__e, __v);
    pyde_store_scalar_raw((const uint8_t *)"total_supply", 12, pyde_enc_finish(&__e));
}

// max_supply_get reads the "max_supply" scalar (zero if unset).
static uint64_t max_supply_get(void) {
    pyde_loaded __l = pyde_load_scalar_raw((const uint8_t *)"max_supply", 10);
    if (__l.len < 0) { return 0; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_u64(&__d);
}
// max_supply_set writes the "max_supply" scalar.
static void max_supply_set(uint64_t __v) {
    pyde_enc __e = pyde_enc_new();
    pyde_enc_u64(&__e, __v);
    pyde_store_scalar_raw((const uint8_t *)"max_supply", 10, pyde_enc_finish(&__e));
}

// next_id_get reads the "next_id" scalar (zero if unset).
static uint64_t next_id_get(void) {
    pyde_loaded __l = pyde_load_scalar_raw((const uint8_t *)"next_id", 7);
    if (__l.len < 0) { return 0; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_u64(&__d);
}
// next_id_set writes the "next_id" scalar.
static void next_id_set(uint64_t __v) {
    pyde_enc __e = pyde_enc_new();
    pyde_enc_u64(&__e, __v);
    pyde_store_scalar_raw((const uint8_t *)"next_id", 7, pyde_enc_finish(&__e));
}

// minter_get reads the "minter" scalar (zero if unset).
static pyde_address minter_get(void) {
    pyde_loaded __l = pyde_load_scalar_raw((const uint8_t *)"minter", 6);
    if (__l.len < 0) { return (pyde_address){{0}}; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_address(&__d);
}
// minter_set writes the "minter" scalar.
static void minter_set(pyde_address __v) {
    pyde_enc __e = pyde_enc_new();
    pyde_enc_address(&__e, __v);
    pyde_store_scalar_raw((const uint8_t *)"minter", 6, pyde_enc_finish(&__e));
}

// manager_get reads the "manager" scalar (zero if unset).
static pyde_address manager_get(void) {
    pyde_loaded __l = pyde_load_scalar_raw((const uint8_t *)"manager", 7);
    if (__l.len < 0) { return (pyde_address){{0}}; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_address(&__d);
}
// manager_set writes the "manager" scalar.
static void manager_set(pyde_address __v) {
    pyde_enc __e = pyde_enc_new();
    pyde_enc_address(&__e, __v);
    pyde_store_scalar_raw((const uint8_t *)"manager", 7, pyde_enc_finish(&__e));
}

// owners_get reads "owners"[keys] (zero if unset).
static pyde_address owners_get(uint64_t __k0) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_u64(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_loaded __l = pyde_load_map1_raw((const uint8_t *)"owners", 6, __kb0.ptr, (int32_t)__kb0.len);
    if (__l.len < 0) { return (pyde_address){{0}}; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_address(&__d);
}
// owners_set writes "owners"[keys] = v.
static void owners_set(uint64_t __k0, pyde_address __v) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_u64(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_address(&__e, __v);
    pyde_store_map1_raw((const uint8_t *)"owners", 6, __kb0.ptr, (int32_t)__kb0.len, pyde_enc_finish(&__e));
}
// owners_delete clears "owners"[keys].
static void owners_delete(uint64_t __k0) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_u64(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_delete_map1_raw((const uint8_t *)"owners", 6, __kb0.ptr, (int32_t)__kb0.len);
}

// balances_get reads "balances"[keys] (zero if unset).
static uint64_t balances_get(pyde_address __k0) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_address(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_loaded __l = pyde_load_map1_raw((const uint8_t *)"balances", 8, __kb0.ptr, (int32_t)__kb0.len);
    if (__l.len < 0) { return 0; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_u64(&__d);
}
// balances_set writes "balances"[keys] = v.
static void balances_set(pyde_address __k0, uint64_t __v) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_address(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_u64(&__e, __v);
    pyde_store_map1_raw((const uint8_t *)"balances", 8, __kb0.ptr, (int32_t)__kb0.len, pyde_enc_finish(&__e));
}
// balances_delete clears "balances"[keys].
static void balances_delete(pyde_address __k0) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_address(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_delete_map1_raw((const uint8_t *)"balances", 8, __kb0.ptr, (int32_t)__kb0.len);
}

// token_approvals_get reads "token_approvals"[keys] (zero if unset).
static pyde_address token_approvals_get(uint64_t __k0) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_u64(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_loaded __l = pyde_load_map1_raw((const uint8_t *)"token_approvals", 15, __kb0.ptr, (int32_t)__kb0.len);
    if (__l.len < 0) { return (pyde_address){{0}}; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_address(&__d);
}
// token_approvals_set writes "token_approvals"[keys] = v.
static void token_approvals_set(uint64_t __k0, pyde_address __v) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_u64(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_address(&__e, __v);
    pyde_store_map1_raw((const uint8_t *)"token_approvals", 15, __kb0.ptr, (int32_t)__kb0.len, pyde_enc_finish(&__e));
}
// token_approvals_delete clears "token_approvals"[keys].
static void token_approvals_delete(uint64_t __k0) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_u64(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_delete_map1_raw((const uint8_t *)"token_approvals", 15, __kb0.ptr, (int32_t)__kb0.len);
}

// operator_approvals_get reads "operator_approvals"[keys] (zero if unset).
static bool operator_approvals_get(pyde_address __k0, pyde_address __k1) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_address(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_enc __ke1 = pyde_enc_new();
    pyde_enc_address(&__ke1, __k1);
    pyde_bytes __kb1 = pyde_enc_finish(&__ke1);
    pyde_loaded __l = pyde_load_map2_raw((const uint8_t *)"operator_approvals", 18, __kb0.ptr, (int32_t)__kb0.len, __kb1.ptr, (int32_t)__kb1.len);
    if (__l.len < 0) { return false; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_bool(&__d);
}
// operator_approvals_set writes "operator_approvals"[keys] = v.
static void operator_approvals_set(pyde_address __k0, pyde_address __k1, bool __v) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_address(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_enc __ke1 = pyde_enc_new();
    pyde_enc_address(&__ke1, __k1);
    pyde_bytes __kb1 = pyde_enc_finish(&__ke1);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_bool(&__e, __v);
    pyde_store_map2_raw((const uint8_t *)"operator_approvals", 18, __kb0.ptr, (int32_t)__kb0.len, __kb1.ptr, (int32_t)__kb1.len, pyde_enc_finish(&__e));
}
// operator_approvals_delete clears "operator_approvals"[keys].
static void operator_approvals_delete(pyde_address __k0, pyde_address __k1) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_address(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_enc __ke1 = pyde_enc_new();
    pyde_enc_address(&__ke1, __k1);
    pyde_bytes __kb1 = pyde_enc_finish(&__ke1);
    pyde_delete_map2_raw((const uint8_t *)"operator_approvals", 18, __kb0.ptr, (int32_t)__kb0.len, __kb1.ptr, (int32_t)__kb1.len);
}

// token_uris_get reads "token_uris"[keys] (zero if unset).
static pyde_string token_uris_get(uint64_t __k0) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_u64(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_loaded __l = pyde_load_map1_raw((const uint8_t *)"token_uris", 10, __kb0.ptr, (int32_t)__kb0.len);
    if (__l.len < 0) { return (pyde_string){0}; }
    pyde_dec __d = pyde_dec_new(__l.data, (uint32_t)__l.len);
    return pyde_dec_string(&__d);
}
// token_uris_set writes "token_uris"[keys] = v.
static void token_uris_set(uint64_t __k0, pyde_string __v) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_u64(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_string(&__e, __v);
    pyde_store_map1_raw((const uint8_t *)"token_uris", 10, __kb0.ptr, (int32_t)__kb0.len, pyde_enc_finish(&__e));
}
// token_uris_delete clears "token_uris"[keys].
static void token_uris_delete(uint64_t __k0) {
    pyde_enc __ke0 = pyde_enc_new();
    pyde_enc_u64(&__ke0, __k0);
    pyde_bytes __kb0 = pyde_enc_finish(&__ke0);
    pyde_delete_map1_raw((const uint8_t *)"token_uris", 10, __kb0.ptr, (int32_t)__kb0.len);
}

// ── Events ─────────────────────────────────────────────────────────

// emit_Approval emits the Approval(address,address,uint64) event.
static void emit_Approval(pyde_address owner, pyde_address approved, uint64_t token_id) {
    uint8_t __topics[32 * 4];
    hash_blake3((const uint8_t *)"Approval(address,address,uint64)", 32, __topics);
    __pyde_memcpy(__topics + 32, owner.bytes, 32);
    __pyde_memcpy(__topics + 64, approved.bytes, 32);
    { pyde_enc __te = pyde_enc_new(); pyde_enc_u64(&__te, token_id); pyde_bytes __tb = pyde_enc_finish(&__te); __pyde_scalar_topic(__tb.ptr, __tb.len, __topics + 96); }
    emit_event(__topics, 4, (const uint8_t *)0, 0);
}

// emit_ApprovalForAll emits the ApprovalForAll(address,address,bool) event.
static void emit_ApprovalForAll(pyde_address owner, pyde_address operator, bool approved) {
    uint8_t __topics[32 * 3];
    hash_blake3((const uint8_t *)"ApprovalForAll(address,address,bool)", 36, __topics);
    __pyde_memcpy(__topics + 32, owner.bytes, 32);
    __pyde_memcpy(__topics + 64, operator.bytes, 32);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_bool(&__e, approved);
    pyde_bytes __dp = pyde_enc_finish(&__e);
    emit_event(__topics, 3, __dp.ptr, (int32_t)__dp.len);
}

// emit_RoleTransfer emits the RoleTransfer(bytes32,address,address) event.
static void emit_RoleTransfer(pyde_bytes32 role, pyde_address holder, pyde_address previous) {
    uint8_t __topics[32 * 3];
    hash_blake3((const uint8_t *)"RoleTransfer(bytes32,address,address)", 37, __topics);
    __pyde_memcpy(__topics + 32, role.bytes, 32);
    __pyde_memcpy(__topics + 64, holder.bytes, 32);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_address(&__e, previous);
    pyde_bytes __dp = pyde_enc_finish(&__e);
    emit_event(__topics, 3, __dp.ptr, (int32_t)__dp.len);
}

// emit_Transfer emits the Transfer(address,address,uint64) event.
static void emit_Transfer(pyde_address from, pyde_address to, uint64_t token_id) {
    uint8_t __topics[32 * 4];
    hash_blake3((const uint8_t *)"Transfer(address,address,uint64)", 32, __topics);
    __pyde_memcpy(__topics + 32, from.bytes, 32);
    __pyde_memcpy(__topics + 64, to.bytes, 32);
    { pyde_enc __te = pyde_enc_new(); pyde_enc_u64(&__te, token_id); pyde_bytes __tb = pyde_enc_finish(&__te); __pyde_scalar_topic(__tb.ptr, __tb.len, __topics + 96); }
    emit_event(__topics, 4, (const uint8_t *)0, 0);
}

// ── Author entry points (define these in main.c) ───────────────────

extern void __approve_impl(pyde_address, uint64_t);
extern uint64_t __balance_of_impl(pyde_address);
extern void __burn_impl(uint64_t);
extern pyde_address __get_approved_impl(uint64_t);
extern void __init_impl(pyde_string, pyde_string, uint64_t);
extern bool __is_approved_for_all_impl(pyde_address, pyde_address);
extern pyde_address __manager_impl(void);
extern uint64_t __max_supply_impl(void);
extern uint64_t __mint_impl(pyde_address, pyde_string);
extern pyde_address __minter_impl(void);
extern pyde_string __name_impl(void);
extern pyde_address __owner_of_impl(uint64_t);
extern void __set_approval_for_all_impl(pyde_address, bool);
extern void __set_manager_impl(pyde_address);
extern void __set_minter_impl(pyde_address);
extern pyde_string __standard_impl(void);
extern pyde_string __symbol_impl(void);
extern pyde_string __token_uri_impl(uint64_t);
extern uint64_t __total_supply_impl(void);
extern uint32_t __transfer_call_impl(pyde_address, uint64_t, pyde_vec_U8);
extern void __transfer_from_impl(pyde_address, pyde_address, uint64_t);

// ── Dispatch ───────────────────────────────────────────────────────

__attribute__((export_name("approve")))
void __pyde_export_approve(void) {
    pyde_dec __d = pyde_args();
    pyde_address __a0 = pyde_dec_address(&__d);
    uint64_t __a1 = pyde_dec_u64(&__d);
    __approve_impl(__a0, __a1);
    pyde_return_nothing();
}

__attribute__((export_name("balance_of")))
void __pyde_export_balance_of(void) {
    pyde_dec __d = pyde_args();
    pyde_address __a0 = pyde_dec_address(&__d);
    uint64_t __r = __balance_of_impl(__a0);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_u64(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("burn")))
void __pyde_export_burn(void) {
    pyde_dec __d = pyde_args();
    uint64_t __a0 = pyde_dec_u64(&__d);
    __burn_impl(__a0);
    pyde_return_nothing();
}

__attribute__((export_name("get_approved")))
void __pyde_export_get_approved(void) {
    pyde_dec __d = pyde_args();
    uint64_t __a0 = pyde_dec_u64(&__d);
    pyde_address __r = __get_approved_impl(__a0);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_address(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("init")))
void __pyde_export_init(void) {
    pyde_dec __d = pyde_args();
    pyde_string __a0 = pyde_dec_string(&__d);
    pyde_string __a1 = pyde_dec_string(&__d);
    uint64_t __a2 = pyde_dec_u64(&__d);
    __init_impl(__a0, __a1, __a2);
    pyde_return_nothing();
}

__attribute__((export_name("is_approved_for_all")))
void __pyde_export_is_approved_for_all(void) {
    pyde_dec __d = pyde_args();
    pyde_address __a0 = pyde_dec_address(&__d);
    pyde_address __a1 = pyde_dec_address(&__d);
    bool __r = __is_approved_for_all_impl(__a0, __a1);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_bool(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("manager")))
void __pyde_export_manager(void) {
    pyde_address __r = __manager_impl();
    pyde_enc __e = pyde_enc_new();
    pyde_enc_address(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("max_supply")))
void __pyde_export_max_supply(void) {
    uint64_t __r = __max_supply_impl();
    pyde_enc __e = pyde_enc_new();
    pyde_enc_u64(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("mint")))
void __pyde_export_mint(void) {
    pyde_dec __d = pyde_args();
    pyde_address __a0 = pyde_dec_address(&__d);
    pyde_string __a1 = pyde_dec_string(&__d);
    uint64_t __r = __mint_impl(__a0, __a1);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_u64(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("minter")))
void __pyde_export_minter(void) {
    pyde_address __r = __minter_impl();
    pyde_enc __e = pyde_enc_new();
    pyde_enc_address(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("name")))
void __pyde_export_name(void) {
    pyde_string __r = __name_impl();
    pyde_enc __e = pyde_enc_new();
    pyde_enc_string(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("owner_of")))
void __pyde_export_owner_of(void) {
    pyde_dec __d = pyde_args();
    uint64_t __a0 = pyde_dec_u64(&__d);
    pyde_address __r = __owner_of_impl(__a0);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_address(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("set_approval_for_all")))
void __pyde_export_set_approval_for_all(void) {
    pyde_dec __d = pyde_args();
    pyde_address __a0 = pyde_dec_address(&__d);
    bool __a1 = pyde_dec_bool(&__d);
    __set_approval_for_all_impl(__a0, __a1);
    pyde_return_nothing();
}

__attribute__((export_name("set_manager")))
void __pyde_export_set_manager(void) {
    pyde_dec __d = pyde_args();
    pyde_address __a0 = pyde_dec_address(&__d);
    __set_manager_impl(__a0);
    pyde_return_nothing();
}

__attribute__((export_name("set_minter")))
void __pyde_export_set_minter(void) {
    pyde_dec __d = pyde_args();
    pyde_address __a0 = pyde_dec_address(&__d);
    __set_minter_impl(__a0);
    pyde_return_nothing();
}

__attribute__((export_name("standard")))
void __pyde_export_standard(void) {
    pyde_string __r = __standard_impl();
    pyde_enc __e = pyde_enc_new();
    pyde_enc_string(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("symbol")))
void __pyde_export_symbol(void) {
    pyde_string __r = __symbol_impl();
    pyde_enc __e = pyde_enc_new();
    pyde_enc_string(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("token_uri")))
void __pyde_export_token_uri(void) {
    pyde_dec __d = pyde_args();
    uint64_t __a0 = pyde_dec_u64(&__d);
    pyde_string __r = __token_uri_impl(__a0);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_string(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("total_supply")))
void __pyde_export_total_supply(void) {
    uint64_t __r = __total_supply_impl();
    pyde_enc __e = pyde_enc_new();
    pyde_enc_u64(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("transfer_call")))
void __pyde_export_transfer_call(void) {
    pyde_dec __d = pyde_args();
    pyde_address __a0 = pyde_dec_address(&__d);
    uint64_t __a1 = pyde_dec_u64(&__d);
    pyde_vec_U8 __a2 = __decodeVecU8(&__d);
    uint32_t __r = __transfer_call_impl(__a0, __a1, __a2);
    pyde_enc __e = pyde_enc_new();
    pyde_enc_u32(&__e, __r);
    pyde_return_bytes(pyde_enc_finish(&__e));
}

__attribute__((export_name("transfer_from")))
void __pyde_export_transfer_from(void) {
    pyde_dec __d = pyde_args();
    pyde_address __a0 = pyde_dec_address(&__d);
    pyde_address __a1 = pyde_dec_address(&__d);
    uint64_t __a2 = pyde_dec_u64(&__d);
    __transfer_from_impl(__a0, __a1, __a2);
    pyde_return_nothing();
}
