// Code generated by otigen. DO NOT EDIT.
//
// Wires this contract's otigen.toml to the Pyde host ABI:
// //go:wasmexport dispatch + typed State accessors. Regenerated
// on every `otigen build`.

//go:build tinygo

package main

import pyde "github.com/pyde-net/pyde-host/go"

var _ = pyde.StatusOK

// ── State ──────────────────────────────────────────────────────────

// State is the typed view of this contract's [state] schema.
var State = struct {
	Counter __stateCounter
}{}

type __stateCounter struct{}

// Get reads the "counter" scalar, returning the zero value if unset.
func (__stateCounter) Get() uint64 {
	b, ok := pyde.LoadScalar("counter")
	if !ok {
		return 0
	}
	d := pyde.NewDecoder(b)
	return d.U64()
}

// Set writes the "counter" scalar.
func (__stateCounter) Set(v uint64) {
	e := pyde.NewEncoder()
	e.U64(v)
	pyde.StoreScalar("counter", e.Finish())
}

// ── Dispatch ───────────────────────────────────────────────────────

//go:wasmexport get
func __pyde_export_get() {
	__r := Get()
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}

//go:wasmexport increment
func __pyde_export_increment() {
	__r := Increment()
	__e := pyde.NewEncoder()
	__e.U64(__r)
	pyde.Return(__e.Finish())
}
